# Generated by Django 4.0 on 2022-01-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_ticket_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content_type',
            field=models.CharField(default='REVIEW', max_length=128),
        ),
        migrations.AddField(
            model_name='ticket',
            name='content_type',
            field=models.CharField(default='TICKET', max_length=128),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
    ]
